### ISSUE TITLE
AST/pretty-printing

### ISSUE THREAD

**Issue by dbarowy** [dbarowy/gCheckCell#1]
If you type in the sample formula on the parserTest.html page, you get:

```
ReferenceExpr ABS(ReferenceExpr ReferenceRange(None, (2,1),(3,1)))
```

But this is a little unclear to me because I don't know what the spaces mean.  Should it be:

  ReferenceExpr(ABS(ReferenceExpr(ReferenceRange(None, (2,1),(3,1)))))

or

  ReferenceExpr.ABS(ReferenceExpr.ReferenceRange(None, (2,1),(3,1)))

I believe it's supposed to be the latter, since that's what the old AST had.  Without being able to read the grammar in its current minified form, it's a little hard to verify, though.

**Comment by atoader** [comment]
I have changed the toString method of the Expression classes so that the output looks like the second example. The output of the ExcelParserConsole is slightly different as it only calls the toString method for the first level of the expression. 
![excelparserconsole](https://f.cloud.github.com/assets/3097909/692046/56760888-dbf1-11e2-8301-14afd8da4749.png)

**Comment by dbarowy** [comment]
OK, great.  I don't see the periods in the pretty-printed string, though.  Do you need to push your changes?

Yeah, if I was only calling toString on the top level, that's a bug on my end.  Good catch.

**Comment by atoader** [comment]
Sorry about that. I pushed the changes to the repo. Can you check?

**Comment by dbarowy** [comment]
Looks good.
