### ISSUE TITLE
Google Spreadsheet script time limit workaround?

### ISSUE THREAD

**Issue by dbarowy** [dbarowy/gCheckCell#6]
Have you worked this out?  If so, please describe your technique here.  It would be nice if you could add to the repo a simple example of a Google Apps Script which needs slightly more than the amount of time allotted, and which correctly deals with this issue.  I think we need to address this problem early on, because if we can't get around it, it may change the direction of the project somewhat.

**Comment by atoader** [comment]
I have made a simple script and added it javascript/Misc/time_limit_solution.js.
I create a hidden sheet to store a serialized javascript object. This object can contain any local or global variables that must be saved in order to restart the execution from a certain point. After storing the object, I create a time trigger that will start the execution of a certain function (the reload function) after a certain amount of time. The reload function will read the data from the sheet, parse it and restart the computation. The hidden sheet that I create has a unique name for the document and will be deleted after the computation finishes. I also use ScriptDb to store the name of this hidden sheet as it isn't always the same. ScriptDb will only store the id of the spreadsheet document and the name of the sheet used to store the information. 
The good news: This solution works, and it should allow up to 50000 users to concurrently use the script.
The bad news: 
- The documentation for the time trigger says that the function might execute as late as 15 minutes after the programmed time. In the tests, I didn't notice any delays, but this is something we should look out for.
